import{a as L,S as C,i as a}from"./assets/vendor-tnUJPedx.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const w="47404996-12b53dec464063fd6255bb496",S="https://pixabay.com/api/";async function p(t,o=1,s=15){const n=`${S}?key=${w}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${s}`;try{return(await L.get(n)).data}catch(e){throw console.error("Error fetching images:",e),e}}function h(t){return t.map(({webformatURL:o,largeImageURL:s,tags:n,likes:e,views:r,comments:l,downloads:b})=>`
        <div class="photo-card">
        <a href="${s}">
            <img src="${o}" alt="${n}" loading="lazy" />
        </a>
        <div class="info">
            <p><b>Likes:</b> ${e}</p>
            <p><b>Views:</b> ${r}</p>
            <p><b>Comments:</b> ${l}</p>
            <p><b>Downloads:</b> ${b}</p>
        </div>
        </div>
        `).join("")}const $=document.querySelector("#search-form"),d=document.querySelector(".gallery"),i=document.querySelector(".load-more"),v=document.querySelector(".loader");let f="",c=1;const u=15,y=new C(".gallery a");$.addEventListener("submit",E);i.addEventListener("click",q);function g(t){v.style.display=t?"block":"none"}function m(t){t?(i.textContent="Loading images, please wait...",i.disabled=!0):(i.textContent="Load more",i.disabled=!1)}async function E(t){if(t.preventDefault(),f=t.currentTarget.elements.searchQuery.value.trim(),!f){a.warning({title:"Warning",message:"Search query cannot be empty!",position:"topRight",titleColor:"#ffff",messageColor:"#ffff"});return}c=1,d.innerHTML="",i.classList.add("hidden"),g(!0);try{const{hits:o,totalHits:s}=await p(f,c,u);if(o.length===0){a.error({title:"Error",message:"No images match your search query!",position:"topRight",titleColor:"#ffff",messageColor:"#ffff"});return}d.innerHTML=h(o),y.refresh(),a.success({title:"Success",message:`Found ${s} images.`,position:"topRight",titleColor:"#ffff",messageColor:"#ffff"}),s>u&&i.classList.remove("hidden")}catch(o){a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight",titleColor:"#ffff",messageColor:"#ffff",backgroundColor:"#ef4040"}),console.error("Error:",o)}finally{g(!1)}}async function q(){c+=1,g(!0),m(!0);try{const{hits:t,totalHits:o}=await p(f,c,u);d.insertAdjacentHTML("beforeend",h(t)),y.refresh(),c*u>=o&&(i.classList.add("hidden"),a.info({title:"Info",message:"You've reached the end of the search results.",position:"topRight",titleColor:"#ffff",messageColor:"#ffff"})),R()}catch(t){a.error({title:"Error",message:"Failed to load more images. Please try again later.",position:"topRight",titleColor:"#ffff",messageColor:"#ffff"}),console.error("Error:",t)}finally{g(!1),m(!1)}}function R(){const{height:t}=d.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
